"""
End-to-end test for the full integrity engine pipeline.

Calls run_pipeline() directly (no subprocess). Uses trust_domain/synthetic/sample
as input_dir so the violation count is deterministic (exactly 7 seeded errors).
coastal_law.toml supplies all other config (firm name, thresholds, rules).
"""
from __future__ import annotations

import datetime
import json
import sys
from pathlib import Path

import pytest

# run.py lives at the project root, one level above tests/
sys.path.insert(0, str(Path(__file__).parent.parent))
from run import run_pipeline

_CONFIG_PATH = Path("trust_domain/config/coastal_law.toml")
_SYNTHETIC_SAMPLE = Path("trust_domain/synthetic/sample")
_GENERATED_AT = datetime.datetime(2026, 6, 25, 10, 30, 0)

_EXPECTED_OUTPUT_FILES = [
    "exception_report.json",
    "exception_report.md",
    "exception_report.pdf",
    "evidence_pack.md",
    "frontend_payload.json",
    "run_log.json",
    "data.ts",
]


@pytest.fixture(scope="module", autouse=True)
def generate_synthetic_sample():
    """Ensure trust_domain/synthetic/sample CSVs exist before any test runs."""
    from trust_domain.synthetic.generator import generate
    generate(_SYNTHETIC_SAMPLE)


@pytest.fixture(scope="module")
def pipeline_result(tmp_path_factory):
    out = tmp_path_factory.mktemp("e2e_output")
    return run_pipeline(
        config_path=_CONFIG_PATH,
        output_dir=out,
        input_dir=_SYNTHETIC_SAMPLE,
        generated_at=_GENERATED_AT,
    )


def test_all_output_files_exist(pipeline_result):
    out = pipeline_result["output_dir"]
    for fname in _EXPECTED_OUTPUT_FILES:
        assert (out / fname).exists(), f"Missing output file: {fname}"


def test_run_log_validation_passed(pipeline_result):
    out = pipeline_result["output_dir"]
    run_log = json.loads((out / "run_log.json").read_text(encoding="utf-8"))
    assert run_log["validation_passed"] is True


def test_exception_report_total_violations_is_7(pipeline_result):
    out = pipeline_result["output_dir"]
    report = json.loads((out / "exception_report.json").read_text(encoding="utf-8"))
    assert report["total_violations"] == 7, (
        f"Expected 7 violations, got {report['total_violations']}"
    )


def test_no_files_written_to_data_sample(pipeline_result):
    data_sample = Path("data/sample")
    if not data_sample.exists():
        return
    actual_names = {f.name for f in data_sample.iterdir()}
    expected_names = {
        "matter_register.csv",
        "client_ledger.csv",
        "trust_bank_statement.csv",
        "reconciliation_summary.csv",
    }
    assert actual_names == expected_names, (
        f"Unexpected files appeared in data/sample/: "
        f"{actual_names - expected_names}"
    )


def test_data_ts_starts_with_autogenerated_comment(pipeline_result):
    out = pipeline_result["output_dir"]
    content = (out / "data.ts").read_text(encoding="utf-8")
    assert content.startswith("// AUTO-GENERATED by Trust Account Integrity Engine"), (
        "data.ts does not start with the expected auto-generated comment"
    )
