"""
TypeScript data file generator for the trust account integrity engine.

Reads a frontend_payload.json and produces a data.ts file that the
LedgerSandbox React frontend imports instead of a live API endpoint.
This bridges the engine to the frontend without a live API — the client
receives a static folder they can open in any browser.

No datetime.now() called here. The generated_at value is read from the
payload's summary.generatedAt field (which was injected upstream).

Usage:
    from trust_domain.reports.generate_data_ts import generate_data_ts
    from pathlib import Path

    path = generate_data_ts(
        payload_path=Path("output/frontend_payload.json"),
        output_path=Path("frontend/src/data.ts"),
    )
"""

from __future__ import annotations

import json
from pathlib import Path

_TEMPLATE = """\
// AUTO-GENERATED by Trust Account Integrity Engine
// Generated: {generated_at}
// Do not edit manually - re-run the engine to update.

import {{ RuleViolation, ComplianceCheck }} from './types';

export const violations: RuleViolation[] = {violations_json};

export const complianceChecks: ComplianceCheck[] = {checks_json};

export const reportSummary = {summary_json};
"""


def generate_data_ts(payload_path: Path, output_path: Path) -> Path:
    """
    Read frontend_payload.json and write a data.ts file.

    Parameters
    ----------
    payload_path   Path to frontend_payload.json (written by adapt_full_report).
    output_path    Full path where data.ts will be written (parent dirs created).

    Returns
    -------
    output_path — the Path that was written.
    """
    payload_path = Path(payload_path)
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    payload = json.loads(payload_path.read_text(encoding="utf-8"))

    generated_at = payload.get("summary", {}).get("generatedAt", "")
    violations_json = json.dumps(payload.get("violations", []), indent=2)
    checks_json = json.dumps(payload.get("complianceChecks", []), indent=2)
    summary_json = json.dumps(payload.get("summary", {}), indent=2)

    content = _TEMPLATE.format(
        generated_at=generated_at,
        violations_json=violations_json,
        checks_json=checks_json,
        summary_json=summary_json,
    )

    output_path.write_text(content, encoding="utf-8")
    return output_path
