"""
PDF exception report generator for NZ trust account integrity reviews.

Produces a self-contained PDF version of the exception report that can be
handed to a client without source code.

PDF structure:
  - Cover block: firm name, period, generated date, total exceptions in large type
  - CRITICAL section: one violation per page (rule_id, nzls_ref, record_id,
    evidence, action required)
  - HIGH section: same structure
  - Summary table: CRITICAL / HIGH / Total counts
  - Footer on every page: CONFIDENTIAL — firm name — period
  - Page numbers on every page: Page N of M

Zero violations: a single "No exceptions found" page.

No datetime.now() or date.today() called here. The caller injects generated_at.

Usage:
    from trust_domain.reports.pdf_report import generate_pdf_report
    import datetime
    from pathlib import Path

    path = generate_pdf_report(
        report_dict=report_dict,
        output_path=Path("output/exception_report.pdf"),
        generated_at=datetime.datetime(2026, 6, 25, 10, 30, 0),
    )
"""

from __future__ import annotations

import datetime
from pathlib import Path

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.pdfgen import canvas as pdfgen_canvas
from reportlab.platypus import (
    BaseDocTemplate,
    Frame,
    PageBreak,
    PageTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
)

_PAGE_WIDTH, _PAGE_HEIGHT = A4
_MARGIN = 20 * mm
_FOOTER_Y = 10 * mm
# The disclaimer sits above the CONFIDENTIAL/page-number row, on its own two
# lines (wrapped so it stays within _MARGIN at 6pt) and far enough above
# _FOOTER_Y that its glyphs never overlap "Page N of M" — verified by
# rendering a real PDF and inspecting it with PyMuPDF during development;
# see tests/test_pdf_report.py::TestFooterGeometry for the checked-in
# regression guard (computed analytically via reportlab's own pdfmetrics,
# since PyMuPDF is not a project dependency).
_DISCLAIMER_Y1 = _FOOTER_Y + 14  # bottom disclaimer line (closest to footer)
_DISCLAIMER_Y2 = _DISCLAIMER_Y1 + 8  # top disclaimer line
_FRAME_BOTTOM = _FOOTER_Y + 14 * mm

_ACTION_TEXT = (
    "Investigate and resolve immediately. "
    "Provide written explanation to TAS within 2 business days."
)

# Wrapped across two lines so it stays within the page margins at 6pt — a
# single line at that size runs wider than the usable page width. Kept as
# module-level constants (rather than local to _make_footer_canvas) so
# tests/test_pdf_report.py can verify their rendered geometry without
# duplicating the literal strings.
_DISCLAIMER_LINE_1 = (
    "This report is generated by TrustSentry, a deterministic "
    "rule-based compliance tool."
)
_DISCLAIMER_LINE_2 = (
    "It does not constitute a legal opinion or a certified audit "
    "under the Lawyers and Conveyancers Act 2006."
)
_DISCLAIMER_FONT_SIZE = 6
_FOOTER_FONT_SIZE = 7
_PAGE_NUM_FONT_SIZE = 8


def _make_footer_canvas(firm_name: str, period: str, demo_watermark: bool = False):
    """Return a Canvas subclass that stamps footer + page numbers on every page."""
    footer_line = (
        f"CONFIDENTIAL — Trust Account Exception Report "
        f"— {firm_name} — {period}"
    )

    class _FooterCanvas(pdfgen_canvas.Canvas):
        def __init__(self, filename, **kwargs):
            super().__init__(filename, **kwargs)
            self._page_states: list = []

        def showPage(self) -> None:
            self._page_states.append(dict(self.__dict__))
            self._startPage()

        def save(self) -> None:
            total = len(self._page_states)
            for page_num, state in enumerate(self._page_states, start=1):
                self.__dict__.update(state)
                if demo_watermark:
                    self._stamp_watermark()
                self._stamp_footer(page_num, total)
                pdfgen_canvas.Canvas.showPage(self)
            pdfgen_canvas.Canvas.save(self)

        def _stamp_watermark(self) -> None:
            self.saveState()
            self.setFont("Helvetica-Bold", 40)
            self.setFillColor(colors.grey, alpha=0.18)
            self.translate(_PAGE_WIDTH / 2, _PAGE_HEIGHT / 2)
            self.rotate(45)
            self.drawCentredString(0, 0, "DEMO — SYNTHETIC DATA ONLY")
            self.restoreState()

        def _stamp_footer(self, page_num: int, total: int) -> None:
            self.saveState()
            self.setFont("Helvetica", _DISCLAIMER_FONT_SIZE)
            self.drawCentredString(_PAGE_WIDTH / 2, _DISCLAIMER_Y2, _DISCLAIMER_LINE_1)
            self.drawCentredString(_PAGE_WIDTH / 2, _DISCLAIMER_Y1, _DISCLAIMER_LINE_2)
            self.setFont("Helvetica", _FOOTER_FONT_SIZE)
            self.drawCentredString(_PAGE_WIDTH / 2, _FOOTER_Y - 3, footer_line)
            self.setFont("Helvetica", _PAGE_NUM_FONT_SIZE)
            self.drawRightString(
                _PAGE_WIDTH - _MARGIN,
                _FOOTER_Y,
                f"Page {page_num} of {total}",
            )
            self.restoreState()

    return _FooterCanvas


def _styles() -> dict:
    base = getSampleStyleSheet()
    return {
        "title": ParagraphStyle(
            "ReportTitle",
            parent=base["Title"],
            fontSize=20,
            spaceAfter=6,
            textColor=colors.HexColor("#1a1a2e"),
        ),
        "cover": ParagraphStyle(
            "CoverField",
            parent=base["Normal"],
            fontSize=12,
            spaceAfter=4,
        ),
        "critical_head": ParagraphStyle(
            "CriticalHead",
            parent=base["Heading1"],
            fontSize=14,
            textColor=colors.HexColor("#c0392b"),
            spaceBefore=8,
            spaceAfter=6,
        ),
        "high_head": ParagraphStyle(
            "HighHead",
            parent=base["Heading1"],
            fontSize=14,
            textColor=colors.HexColor("#d35400"),
            spaceBefore=8,
            spaceAfter=6,
        ),
        "violation_label": ParagraphStyle(
            "ViolationLabel",
            parent=base["Heading2"],
            fontSize=12,
            spaceAfter=4,
        ),
        "body": base["Normal"],
    }


def _violation_block(v: dict, st: dict) -> list:
    """Return Flowables for one violation (label + detail table)."""
    action = (
        f"ESCALATE — {_ACTION_TEXT}"
        if v.get("recommended_action") == "ESCALATE"
        else v.get("recommended_action", "REVIEW")
    )
    rows = [
        [Paragraph("<b>Rule ID</b>", st["body"]),     Paragraph(v["rule_id"], st["body"])],
        [Paragraph("<b>Regulation</b>", st["body"]),  Paragraph(v["nzls_ref"], st["body"])],
        [Paragraph("<b>Record</b>", st["body"]),      Paragraph(v["record_id"], st["body"])],
        [Paragraph("<b>Finding</b>", st["body"]),     Paragraph(v["evidence"], st["body"])],
        [Paragraph("<b>Action</b>", st["body"]),      Paragraph(action, st["body"])],
    ]
    tbl = Table(rows, colWidths=[38 * mm, 132 * mm])
    tbl.setStyle(TableStyle([
        ("VALIGN",      (0, 0), (-1, -1), "TOP"),
        ("GRID",        (0, 0), (-1, -1), 0.25, colors.lightgrey),
        ("BACKGROUND",  (0, 0), (0, -1), colors.HexColor("#f5f5f5")),
        ("FONTNAME",    (0, 0), (0, -1), "Helvetica-Bold"),
        ("LEFTPADDING", (0, 0), (-1, -1), 4),
        ("RIGHTPADDING",(0, 0), (-1, -1), 4),
        ("TOPPADDING",  (0, 0), (-1, -1), 4),
        ("BOTTOMPADDING",(0, 0), (-1, -1), 4),
    ]))
    return [
        Paragraph(f"{v['severity']} — {v['label']}", st["violation_label"]),
        Spacer(1, 3 * mm),
        tbl,
    ]


def _cover_block_lines(
    *, firm_name: str, period: str, date_str: str, sensitivity: str,
    total: int, n_critical: int, n_high: int,
) -> list[str]:
    """
    The cover block's paragraph text, in render order, as reportlab
    mini-markup strings. Extracted from generate_pdf_report() so the exact
    content can be unit-tested directly — flowable text lands in a
    compressed PDF content stream, so grepping the rendered bytes (as
    TestGeneratePdfReport.test_pdf_contains_firm_name does for the
    uncompressed /Info metadata) does not work for on-page text; this
    mirrors TestFooterGeometry's approach of pinning real content via an
    importable function rather than parsing rendered PDF bytes.
    """
    return [
        f"<b>Firm:</b> {firm_name}",
        f"<b>Period:</b> {period}",
        f"<b>Generated:</b> {date_str}",
        f"<b>Reference date:</b> {date_str}",
        f"<b>Sensitivity:</b> {sensitivity.capitalize()}",
        "<i>For internal use — not a substitute for professional audit</i>",
        f"<b>Total exceptions:</b> {total} ({n_critical} CRITICAL, {n_high} HIGH)",
    ]


def generate_pdf_report(
    report_dict: dict,
    output_path: Path,
    generated_at: datetime.datetime,
    demo_watermark: bool = False,
) -> Path:
    """
    Generate a PDF exception report from a structured report dict.

    Parameters
    ----------
    report_dict    The dict returned by build_report_dict() / exception_report.json.
    output_path    Full path where the PDF will be written (parent dirs created).
    generated_at   Injected datetime — never sampled inside this function.
    demo_watermark  When True, stamp a diagonal "DEMO — SYNTHETIC DATA ONLY"
                     watermark on every page. Default False (on-premise/local
                     runs never set this).

    Returns
    -------
    output_path — the Path that was written.
    """
    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    firm_name   = report_dict["firm_name"]
    period      = report_dict["report_period"]
    total       = report_dict["total_violations"]
    n_critical  = report_dict["critical_count"]
    n_high      = report_dict["high_count"]
    sensitivity = report_dict.get("sensitivity", "standard")
    violations  = report_dict["violations"]
    date_str    = generated_at.strftime("%d %B %Y")

    st = _styles()
    footer_canvas = _make_footer_canvas(firm_name, period, demo_watermark=demo_watermark)

    frame = Frame(
        _MARGIN,
        _FRAME_BOTTOM,
        _PAGE_WIDTH - 2 * _MARGIN,
        _PAGE_HEIGHT - _MARGIN - _FRAME_BOTTOM,
        id="main",
    )
    doc = BaseDocTemplate(
        str(output_path),
        pagesize=A4,
        title="TrustSentry Pre-Inspection Compliance Report",
        author=firm_name,
        subject=f"TrustSentry Pre-Inspection Compliance Report — {period}",
        creator="Trust Account Integrity Engine",
    )
    doc.addPageTemplates([PageTemplate(id="main", frames=[frame])])

    story: list = []

    # Cover block
    story.append(Paragraph("TrustSentry Pre-Inspection Compliance Report", st["title"]))
    story.append(Spacer(1, 4 * mm))
    for line in _cover_block_lines(
        firm_name=firm_name, period=period, date_str=date_str,
        sensitivity=sensitivity, total=total, n_critical=n_critical, n_high=n_high,
    ):
        story.append(Paragraph(line, st["cover"]))
    story.append(Spacer(1, 8 * mm))

    if total == 0:
        story.append(Paragraph("No exceptions found", st["critical_head"]))
        story.append(Paragraph(
            f"This trust account passed all integrity checks for {period}.",
            st["body"],
        ))
    else:
        critical_items = [v for v in violations if v["severity"] == "CRITICAL"]
        high_items     = [v for v in violations if v["severity"] == "HIGH"]

        if critical_items:
            story.append(Paragraph("CRITICAL Exceptions", st["critical_head"]))
            for i, v in enumerate(critical_items):
                if i > 0:
                    story.append(PageBreak())
                story.extend(_violation_block(v, st))

        if high_items:
            story.append(PageBreak())
            story.append(Paragraph("HIGH Exceptions", st["high_head"]))
            for i, v in enumerate(high_items):
                if i > 0:
                    story.append(PageBreak())
                story.extend(_violation_block(v, st))

        # Summary table
        story.append(PageBreak())
        story.append(Paragraph("Summary", st["critical_head"]))
        summary_rows = [
            [Paragraph("<b>Severity</b>", st["body"]), Paragraph("<b>Count</b>", st["body"])],
            [Paragraph("CRITICAL", st["body"]),         Paragraph(str(n_critical), st["body"])],
            [Paragraph("HIGH",     st["body"]),         Paragraph(str(n_high),     st["body"])],
            [Paragraph("<b>Total</b>", st["body"]),     Paragraph(f"<b>{total}</b>", st["body"])],
        ]
        tbl = Table(summary_rows, colWidths=[80 * mm, 40 * mm])
        tbl.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#2c3e50")),
            ("TEXTCOLOR",  (0, 0), (-1, 0), colors.white),
            ("FONTNAME",   (0, 0), (-1, 0), "Helvetica-Bold"),
            ("GRID",       (0, 0), (-1, -1), 0.5, colors.grey),
            ("ALIGN",      (1, 0), (1, -1), "CENTER"),
            ("PADDING",    (0, 0), (-1, -1), 6),
        ]))
        story.append(tbl)

    doc.build(story, canvasmaker=footer_canvas)
    return output_path
